package dsr_test

// rv_canonical_vector_test.go — canonical form vector tests for RV receipts.
// These tests require fixture files generated by the wallow monorepo.
// Run: make verify-vector-parity  to generate fixtures and run this test.
