package verify_test

// adversarial_test.go — cross-type negative tests for receipt type enforcement.
//
// Each test proves that a receipt signed as type A cannot be presented as type B
// and pass signature verification. The mechanism is that each canonical form
// includes type-specific fields (and sometimes the "type" key itself), so the
// byte sequence signed for type A will never match the byte sequence constructed
// for type B.
//
// Design notes:
//
//   - All tests use a PINNED ed25519 key pair derived from a fixed 32-byte seed.
//     This eliminates ephemeral-key tautology risk: the key pair is stable across
//     runs and not generated by the test framework's entropy source.
//
//   - Envelopes carry the fields required by BOTH type A and type B, so that
//     dsr.CanonicalPayload succeeds for the claimed type B. The test then proves
//     the failure is a genuine signature mismatch, not a missing-field error.
//     For example, R1-L → R1: the envelope carries repository and pr_number so
//     attributionCanonical can run — but the signed bytes are still wrong.
//
//   - assertInvalid and dsrerrors are defined/imported in verify_test.go
//     (same package verify_test).

import (
	"bytes"
	"crypto/ed25519"
	"encoding/base64"
	"strings"
	"testing"

	"github.com/deja-app/dsr-verifier-cli/internal/dsr"
	dsrerrors "github.com/deja-app/dsr-verifier-cli/internal/errors"
	"github.com/deja-app/dsr-verifier-cli/internal/verify"
)

// ─── Pinned key helpers ───────────────────────────────────────────────────────

// pinnedEd25519Keys returns a deterministic ed25519 key pair from a fixed seed.
// The seed is 32 repeated 0x42 bytes; the pair is stable across all runs.
func pinnedEd25519Keys() (ed25519.PublicKey, ed25519.PrivateKey) {
	seed := bytes.Repeat([]byte{0x42}, ed25519.SeedSize)
	priv := ed25519.NewKeyFromSeed(seed)
	return priv.Public().(ed25519.PublicKey), priv
}

// pinnedProvidedKey wraps the pinned public key in a PublicKeyWithID so it
// can be passed directly to verify.Signature without going through file parsing.
func pinnedProvidedKey() *verify.PublicKeyWithID {
	pub, _ := pinnedEd25519Keys()
	return &verify.PublicKeyWithID{Key: pub}
}

// signPinned computes the canonical payload for e, signs it with the pinned
// ed25519 private key, and stores the base64 signature in e.Signature.
// SignatureAlgorithm is set to "ed25519-v1" before the canonical payload is
// computed, so canonical forms that include the signing_algorithm key (R1)
// will capture it correctly.
func signPinned(t *testing.T, e *dsr.Envelope) {
	t.Helper()
	_, priv := pinnedEd25519Keys()
	algo := dsr.AlgoED25519V1
	e.SignatureAlgorithm = &algo
	canonical, err := dsr.CanonicalPayload(e)
	if err != nil {
		t.Fatalf("signPinned: CanonicalPayload(%s) failed: %v", e.Type, err)
	}
	sig := ed25519.Sign(priv, []byte(canonical))
	e.Signature = base64.StdEncoding.EncodeToString(sig)
}

// ─── Envelope builders for adversarial tests ──────────────────────────────────
//
// Each builder returns an envelope that is valid for its own type AND carries
// the extra fields required by the cross-type claim. This lets the verification
// exercise the crypto path rather than short-circuiting on a missing-field error.

// adversarialR1L is a minimal R1-L envelope extended with R1-required fields
// (repository, pr_number, ccs_score, confidence, matched) so that switching
// its type to R1 allows attributionCanonical to run.
func adversarialR1L() *dsr.Envelope {
	issuedAt := "2026-07-17T00:00:00.000Z"
	count := int64(3)
	highest := "0.720"
	zone := "deja-test-zone"
	vault := "00000000-0000-0000-0000-000000000001"
	repo := "adversarial/test-repo"
	pr := int64(1)
	ccs := "0.7200"
	conf := "LOW"
	matched := "false"
	return &dsr.Envelope{
		DSRVersion:     "DSR/1.0",
		Type:           dsr.TypeR1L,
		ReceiptID:      "ADV-R1L-001",
		VaultID:        vault,
		Timestamp:      issuedAt,
		Actor:          "system:sde",
		Origin:         "production",
		Signature:      "placeholder",
		IssuedAt:       &issuedAt,
		CandidateCount: &count,
		HighestCcs:     &highest,
		ServiceZone:    &zone,
		// R1-required extras so type-B canonical construction succeeds:
		Repository: &repo,
		PRNumber:   &pr,
		CCSScore:   &ccs,
		Confidence: &conf,
		Matched:    &matched,
	}
}

// adversarialR1N is a minimal R1-N envelope extended with R1-required fields.
func adversarialR1N() *dsr.Envelope {
	issuedAt := "2026-07-16T00:00:00.000Z"
	lookback := int64(30)
	prsEval := int64(0)
	highest := "0.000"
	zone := "deja-test-zone"
	vault := "00000000-0000-0000-0000-000000000001"
	repo := "adversarial/test-repo"
	pr := int64(1)
	ccs := "0.0000"
	conf := "LOW"
	matched := "false"
	return &dsr.Envelope{
		DSRVersion:          "DSR/1.0.3",
		Type:                dsr.TypeR1N,
		ReceiptID:           "ADV-R1N-001",
		VaultID:             vault,
		Timestamp:           issuedAt,
		Actor:               "system:sde",
		Origin:              "production",
		Signature:           "placeholder",
		IssuedAt:            &issuedAt,
		HighestCandidateCcs: &highest,
		LookbackDays:        &lookback,
		PrsEvaluated:        &prsEval,
		ServiceZone:         &zone,
		// R1-required extras:
		Repository: &repo,
		PRNumber:   &pr,
		CCSScore:   &ccs,
		Confidence: &conf,
		Matched:    &matched,
	}
}

// adversarialR1 is a minimal R1 envelope extended with RG-required fields
// (organization_id, change_type, prior_state_hash, new_state_hash) so that
// switching its type to RG allows governanceCanonical to run.
func adversarialR1() *dsr.Envelope {
	issuedAt := "2026-07-17T00:00:00.000Z"
	repo := "adversarial/test-repo"
	pr := int64(1)
	ccs := "0.8750"
	conf := "HIGH"
	matched := "true"
	zone := "deja-test-zone"
	changeType := "source_control_connected:github"
	priorStateHash := strings.Repeat("1", 64)
	newStateHash := strings.Repeat("a", 64)
	return &dsr.Envelope{
		DSRVersion:     "DSR/1.0",
		Type:           dsr.TypeR1,
		ReceiptID:      "ADV-R1-001",
		VaultID:        "vlt-adversarial",
		OrganizationID: "aaaabbbb-cccc-dddd-eeee-ffffaaaabbbb",
		Timestamp:      issuedAt,
		Actor:          "actor@example.com",
		Origin:         "github",
		Signature:      "placeholder",
		IssuedAt:       &issuedAt,
		Repository:     &repo,
		PRNumber:       &pr,
		CCSScore:       &ccs,
		Confidence:     &conf,
		Matched:        &matched,
		ServiceZone:    &zone,
		// RG-required extras so type-B canonical construction succeeds:
		ChangeType:     &changeType,
		PriorStateHash: &priorStateHash,
		NewStateHash:   &newStateHash,
	}
}

// adversarialRG is a minimal RG envelope extended with R1-required fields
// (repository, pr_number, ccs_score, confidence, matched) so that switching
// its type to R1 allows attributionCanonical to run.
func adversarialRG() *dsr.Envelope {
	issuedAt := "2026-01-01T00:00:00.000Z"
	changeType := "source_control_connected:github"
	priorStateHash := strings.Repeat("1", 64)
	newStateHash := strings.Repeat("a", 64)
	repo := "adversarial/test-repo"
	pr := int64(1)
	ccs := "0.8750"
	conf := "HIGH"
	matched := "true"
	zone := "deja-test-zone"
	return &dsr.Envelope{
		DSRVersion:     "DSR/1.0",
		Type:           dsr.TypeRG,
		ReceiptID:      "ADV-RG-001",
		OrganizationID: "aaaabbbb-cccc-dddd-eeee-ffffaaaabbbb",
		Actor:          "system:onboarding",
		Origin:         "production",
		Signature:      "placeholder",
		IssuedAt:       &issuedAt,
		ChangeType:     &changeType,
		PriorStateHash: &priorStateHash,
		NewStateHash:   &newStateHash,
		// R1-required extras so type-B canonical construction succeeds:
		Repository:  &repo,
		PRNumber:    &pr,
		CCSScore:    &ccs,
		Confidence:  &conf,
		Matched:     &matched,
		ServiceZone: &zone,
	}
}

// ─── Cross-type negative pairs ────────────────────────────────────────────────
//
// Convention: TestAdversarial_CrossType_<SignedAs>_Claim<ClaimedAs>_Fails.
//
// Each test:
//   1. Builds and signs envelope A with the pinned key.
//   2. Shallow-copies A into envelope B, changing only the Type field.
//   3. Calls verify.Signature(B, pinnedProvidedKey()) and asserts Valid=false.
//
// The failure is always a genuine crypto mismatch: the canonical payload computed
// for type B differs from the bytes that were signed for type A.

// TestAdversarial_CrossType_R1L_ClaimR1_Fails proves that an R1-L receipt
// signed with lowConfidenceCanonical bytes cannot verify as an R1 receipt.
//
// R1-L canonical:   {candidate_count, highest_ccs, issued_at, receipt_id, service_zone, type:"R1-L", vault_id, version}
// R1 canonical:     {ccs_score, confidence, error_class, issued_at, matched, missing_field, pr_number, repository, service_zone}
//
// The byte sequences are completely different; the signature must fail.
func TestAdversarial_CrossType_R1L_ClaimR1_Fails(t *testing.T) {
	eA := adversarialR1L()
	signPinned(t, eA)

	eB := *eA // shallow copy — Type changes, Signature and other pointers stay
	eB.Type = dsr.TypeR1

	result := verify.Signature(&eB, pinnedProvidedKey())
	assertInvalid(t, "R1-L-signed receipt claimed as R1", result.Valid, result.Err, dsrerrors.SignatureInvalid)
}

// TestAdversarial_CrossType_R1N_ClaimR1_Fails proves that an R1-N receipt
// signed with noAttributionCanonical bytes cannot verify as an R1 receipt.
//
// R1-N canonical:   {highest_candidate_ccs, issued_at, lookback_days, prs_evaluated, receipt_id, service_zone, type:"R1-N", vault_id, version}
// R1 canonical:     {ccs_score, confidence, error_class, issued_at, matched, missing_field, pr_number, repository, service_zone}
func TestAdversarial_CrossType_R1N_ClaimR1_Fails(t *testing.T) {
	eA := adversarialR1N()
	signPinned(t, eA)

	eB := *eA
	eB.Type = dsr.TypeR1

	result := verify.Signature(&eB, pinnedProvidedKey())
	assertInvalid(t, "R1-N-signed receipt claimed as R1", result.Valid, result.Err, dsrerrors.SignatureInvalid)
}

// TestAdversarial_CrossType_R1_ClaimR1L_Fails proves that an R1 receipt
// signed with attributionCanonical bytes cannot verify as an R1-L receipt.
//
// R1 canonical:     {ccs_score, confidence, error_class, issued_at, matched, missing_field, pr_number, repository, service_zone, signing_algorithm}
// R1-L canonical:   {candidate_count:0, highest_ccs:"0.000", issued_at, receipt_id, service_zone, type:"R1-L", vault_id, version}
//
// lowConfidenceCanonical succeeds on the R1 envelope (nil R1-L fields → defaults),
// but the canonical bytes are structurally different from the signed R1 form.
func TestAdversarial_CrossType_R1_ClaimR1L_Fails(t *testing.T) {
	eA := adversarialR1()
	signPinned(t, eA)

	eB := *eA
	eB.Type = dsr.TypeR1L

	result := verify.Signature(&eB, pinnedProvidedKey())
	assertInvalid(t, "R1-signed receipt claimed as R1-L", result.Valid, result.Err, dsrerrors.SignatureInvalid)
}

// TestAdversarial_CrossType_R1_ClaimR1N_Fails proves that an R1 receipt
// signed with attributionCanonical bytes cannot verify as an R1-N receipt.
//
// R1-N canonical:   {highest_candidate_ccs:"0.000", issued_at, lookback_days:0, prs_evaluated:0, receipt_id, service_zone, type:"R1-N", vault_id, version}
//
// noAttributionCanonical succeeds on the R1 envelope (nil R1-N fields → defaults),
// but the canonical bytes are structurally different from the signed R1 form.
func TestAdversarial_CrossType_R1_ClaimR1N_Fails(t *testing.T) {
	eA := adversarialR1()
	signPinned(t, eA)

	eB := *eA
	eB.Type = dsr.TypeR1N

	result := verify.Signature(&eB, pinnedProvidedKey())
	assertInvalid(t, "R1-signed receipt claimed as R1-N", result.Valid, result.Err, dsrerrors.SignatureInvalid)
}

// TestAdversarial_CrossType_RG_ClaimR1_Fails proves that an RG receipt
// signed with governanceCanonical bytes cannot verify as an R1 receipt.
//
// RG canonical:     {actor, change_type, issued_at, new_state_hash, organization_id, prior_state_hash, receipt_id, type:"RG", version}
// R1 canonical:     {ccs_score, confidence, error_class, issued_at, matched, missing_field, pr_number, repository, service_zone}
//
// attributionCanonical succeeds (repository and pr_number are present),
// but the signed bytes come from a completely different field set.
func TestAdversarial_CrossType_RG_ClaimR1_Fails(t *testing.T) {
	eA := adversarialRG()
	signPinned(t, eA)

	eB := *eA
	eB.Type = dsr.TypeR1

	result := verify.Signature(&eB, pinnedProvidedKey())
	assertInvalid(t, "RG-signed receipt claimed as R1", result.Valid, result.Err, dsrerrors.SignatureInvalid)
}

// TestAdversarial_CrossType_R1_ClaimRG_Fails proves that an R1 receipt
// signed with attributionCanonical bytes cannot verify as an RG receipt.
//
// R1 canonical:     {ccs_score, confidence, error_class, issued_at, matched, missing_field, pr_number, repository, service_zone, signing_algorithm}
// RG canonical:     {actor, change_type, issued_at, new_state_hash, organization_id, prior_state_hash, receipt_id, type:"RG", version}
//
// governanceCanonical succeeds (change_type, prior_state_hash, new_state_hash are
// present on adversarialR1), but the canonical bytes differ entirely from R1.
func TestAdversarial_CrossType_R1_ClaimRG_Fails(t *testing.T) {
	eA := adversarialR1()
	signPinned(t, eA)

	eB := *eA
	eB.Type = dsr.TypeRG

	result := verify.Signature(&eB, pinnedProvidedKey())
	assertInvalid(t, "R1-signed receipt claimed as RG", result.Valid, result.Err, dsrerrors.SignatureInvalid)
}
